### PR TITLE
Update tc_2019_2020 to support ahv mode

### PR DESCRIPTION
**Pull request by Junefen**
Update error message list for ahv mode, it shows "HTTP Auth Failed" when configure bad username and password.
But because there is also issue for the two cases, so will not attach the test result.

### CODE REVIEW

**Comment by hkx303** [comment]
> it shows "HTTP Auth Failed" when configure bad username and password.  

So is it expected?

**Review by hkx303 — APPROVED** [review]
Looks good to me.

**Comment by Junefen** [comment]
> > it shows "HTTP Auth Failed" when configure bad username and password.
> 
> So is it expected?

@hkx303 Yes, I think it's expected, from "HTTP Auth Failed" we can know it's authentication error. And the behaviors/logs are different for hypervisors because virt-who gets different responses when configured bad username/passord, so we just defined a msg_list in code.

**Comment by hkx303** [comment]
Make sense :)

**Pull request merged**
